server:
  port: 8088

# 热部署生效
spring.devtools.restart.enabled: true
# 设置重启的目录
# spring.devtools.restart.additional-paths: src/main/java
# classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**
# 页面热部署
spring.thymeleaf.cache: false

spring:
  datasource:
#    username: ***
#    password: ***
#    url: jdbc:mysql://localhost:3306/book_lib?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: ENC(ykYC+9HTgKhPeLq42jO7mw==)
    password: ENC(uWQFqJ4DD4niAYctp8368w==)
    url: ENC(WxNL4+an5PhUgExz+F6ecgjuw9Q0SbR9m9MZ1XHhgiY/kZ825otmerUsJLTffxSu6szlqBaIa5wDo0e9NfMWOiW3As0KdhUOGLPU4uoh+a846D3zBGH9XnFgQEZPBFWF4PGUCseLEq84O472OVbiL0iZqxP7NeV8)
#    url: jdbc:mysql://172.24.170.241:3306/book_lib?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource

#  data:
#    elasticsearch:
#      cluster-name: booklib_elasticsearch
#      cluster-nodes: 127.0.0.1:9300
#      repositories:
#        enabled: true
#      properties:
#        path:
#          logs: ./elasticsearch/log #elasticsearch日志存储目录
#          data: ./elasticsearch/data #elasticsearch数据存储目录

#jasypt加密的密匙
jasypt:
  encryptor:
    password: laystbzqzygwcs

mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: cn.rjguanwen.cypress.booklibrary.entity
  config-location: classpath:mybatis/mybatis-config.xml

# pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false

# 日志配置
logging:
  level:
    root: info
    cn:
      rjguanwen:
        # show sql
        mapper: debug
  file: C:/tmp/logs/booklib/booklibrary.log
#  pattern:
#    console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#    file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n

swagger:
  enabled: true
